state_machine_executor:
  ros__parameters:
    paths:
      path_A: [
        -11.25, 11.25,  11.25, 11.25,  11.25, 9.75,  -11.25, 9.75,
        -11.25, 8.25,   11.25, 8.25,   11.25, 6.75,  -11.25, 6.75,
        -11.25, 5.25,   11.25, 5.25,   11.25, 3.75,  -11.25, 3.75
      ]
      path_B: [
        -11.25, -3.75,  11.25, -3.75,  11.25, -5.25, -11.25, -5.25,
        -11.25, -6.75,  11.25, -6.75,  11.25, -8.25, -11.25, -8.25,
        -11.25, -9.75,  11.25, -9.75,  11.25, -11.25,-11.25, -11.25
      ]
